- Compressonator/Header/Compressonator.h
* ATI2N is primarily for tangent space, not object space normal maps
* BC5 actually matches ATI2N_XY, not ATI2N
> Updated BC5/ATI2N format comments

- Compressonator/Applications/CompressonatorCLI/Source/CompressonatorCLI.cpp
- Compressonator/Applications/_Plugins/Common/cmdline.cpp
- Compressonator/Applications/_Plugins/Common/cmdline.h
Hi, we use the tool every day. Now with folder support it works even faster, but the problem is that we want output in .ktx or other file format and it defaults to .dds.
I modify this in order to support valid file output with parameter "-fx".
Please tell me what you think.
Thanks Dean.
> Support for CLI output directory extension.

- Compressonator/Source/Codec/ASTC/ASTC_Encode_Kernel.cpp
VS2019 complains about that the arguments to a braced initializer list for a `float4` must be `float`s, but `sqrt()` returns a double.
> Fix missing double -> float cast

- Compressonator/Applications/_Plugins/Common/cmdline.cpp
Without this patch, the project does not build with newer compiler
versions like gcc 9.
> Ignore format-security error

- Compressonator/CMP_Core/shaders/BC7_Encode_Kernel.cpp
implicit casts to explicit casts, now no more warnings appear regarding this issue
> fixed implicit casts to explicit casts in BC7_Encode_Kernel.cpp

- Compressonator/Applications/_Plugins/CCMP_Encode/HPC/Compute_CPU_HPC.cpp
First of all, this fix has been done from debugging BC7 HPC codepath, where tp->run has already initialized with false value.
In my case I tested the encoding on a FX-8320 and i7-8sthing (W10: 18363) both with 8 threads, where in both cases first 8 blocks on encoding was likely (non deterministic) garbage. Some of the first 8 blocks was fine, but most of them not (garbage).
So I will begin with my explanation of the bug based on the old code.
Let's say the just created thread (around at line 100 std::thread is called) is created and "runs" first to line where `tp->run = false;` executes. Everything is fine :D.
Now let's say it doesn't "runs" first but command `m_EncodeParameterStorage[threadIndex].run = true;` (around at line 179) runs first, Then encoding has a "green" light but if …
> Fix for N first blocks garbage BC7 encodings, for N threaded CPUs.

- Compressonator/Applications/_Plugins/Common/UtilFuncs.cpp
- Compressonator/Applications/_Plugins/Common/UtilFuncs.h
- Compressonator/CMP_Core/test/BlockConstants.h
- Compressonator/CMP_Core/test/CMakeLists.txt
- Compressonator/CMP_Core/test/CompressonatorTests.cpp
UtilFuncs: HalfToFloat changed the signature to non-static and added HalfToFloat to UtilFuncs.h.
The CompressonatorTests.cpp does now use the HalfToFloat function instead of intrinsic.
> Added BC4 and BC5 tests

- Compressonator/Applications/_Plugins/Common/cmdline.cpp
- Compressonator/Applications/_Plugins/Common/cmdline.h
- Compressonator/Applications/_Plugins/Common/gltf/tiny_gltf2_utils.cpp
- Compressonator/CMP_CompressonatorLib/Common.h
- Compressonator/CMP_CompressonatorLib/Compressonator.h
- Compressonator/CMP_Framework/Compute_Base.cpp
This adds the `-compress-gltf-images` flag to the CLI version. It will cause compression of images referenced in glTF file, save those as DDS files and use [MSFT_texture_dds](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/MSFT_texture_dds) to reference compressed variants in outputted glTF-file.
TextureIO is used for file opening and saving DDS (there was already a comment that this feature should use it).
For compression this uses "Compressonator Framework"'s CMP_ProcessTexture-functions, which seems to only work with BC-formats right now. This choice was made as I couldn't get other ways to produce the `CMP_MipSet` required by TextureIO.
> Compress images inside glTF 2.0

- Compressonator/CMP_Core/shaders/BC1_Encode_kernel.cpp
- Compressonator/CMP_Core/shaders/BC2_Encode_kernel.cpp
- Compressonator/CMP_Core/shaders/BC3_Encode_kernel.cpp
- Compressonator/CMP_Core/shaders/BC4_Encode_kernel.cpp
- Compressonator/CMP_Core/shaders/BC5_Encode_kernel.cpp
- Compressonator/CMP_Core/shaders/BC6_Encode_kernel.cpp
- Compressonator/CMP_Core/shaders/BC7_Encode_Kernel.cpp
- Compressonator/CMP_Core/source/CMP_Core.h
See https://github.com/GPUOpen-Tools/compressonator/issues/115
Add the missing pieces, however some may not take effect until next point release (ie: BC7 Gamma, BC4&5 signedness).
Also fix issue with BC6 option creation trampling callers stack.
> Add missing options to API

- CMP_Core/shaders/BC5_Encode_kernel.cpp
In function CompressBlockBC5_DualChannel_Internal, the conversion from uint8 srcBlockR/srcBlockG to float srcAlphaRF/srcAlphaGF is not complete.
> Fix unsigned int8 to float conversion in CMP_Core RG to BC5 compression function

- Applications/CompressonatorGUI/Components/cpImageCompare.cpp
- Applications/CompressonatorGUI/Components/cpImageCompare.h
- Applications/CompressonatorGUI/VS2017/MainApp.vcxproj
- Applications/_Plugins/CAnalysis/Analysis/CAnalysis.cpp
- Applications/_Plugins/CAnalysis/Analysis/VS2017/CAnalysis.vcxproj
- Compressonator_Root.props
- External/rapidxml/CMakeLists.txt
- External/rapidxml/cmp_rapidxml.hpp
- build/fetch_dependencies.py
First step to removing boost as a dependency. RapidXML is the what boost uses in it's `property_tree` so the performance should be pretty comparable. With boost removed as a dependency, compiling for all platforms becomes way simpler.
> Replaced boost proeprty_map with rapidxml

- cmp_core/shaders/bcn_common_kernel.h
Unnamed classes may not contain member functions in C++. This triggers a warning in MSVC in C++14/17 mode (C5208) which turns into an error in C++20 mode C7626.
See: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5208?view=msvc-170
> Fix compile error with /c++:20.

- cmp_core/shaders/common_def.h
In OpenCL, "unsigned long long" corresponds to a 128bit integer and is a reserved type name: https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_C.html#reserved-data-types
The Nvidia CUDA implementation of the OpenCL C compiler reported the following error:
```
common_def.h:333:18: error: use of 128 bit type is not supported
typedef unsigned long long CGU_UINT64;
^
```
I don't think this change impacts other compilers, but I haven't thoroughly tested it.
> OpenCL: Changed CGU_UINT64 typedef back to "unsigned long"

- applications/_plugins/common/textureio.cpp
There is a strange difference between CMP_LoadTexture and AMDLoadMIPSTextureImage in which the later requires QT for simple formats. The goal being to have a minimal and useful dev CLI tool. Plus QT is a hot mess that reasonable people wouldn't install.
> - fall back to stb since function exists for CLI

- CMakeLists.txt
- applications/_plugins/common/cmdline.cpp
- examples/cmp_prototype/CMakeLists.txt
- external/glfw/CMakeLists.txt
- scripts/fetch_dependencies.py
Reworked how files are downloaded in the fetch dependencies script, removing the use of urllib.request.urlretrieve which would have permission issues on Linux.
Changed external GLFW download from a Windows-only zip file, to downloading and building from the GitHub repository. Enabling use by both Windows and Linux.
> Fix issues with Linux build

- .github/workflows/cmake.yml
- CMakeLists.txt
- examples/cmp_prototype/CMakeLists.txt
- scripts/windows_build_sdk.bat
The CMake YAML file was modified to add a job to build Compressonator Framework. It builds all the variations of the Framework using the solution files in the VS2019 folder and collects them into a folder structure that is identical to the release build, making it easy to copy and paste the folder structure into existing installations to update them. The packages created by this build _do not_ contain extra licence information or DLLs so an existing installation is required.
> Compressonator Framework Build Added to GitHub Action File

- cmp_compressonatorlib/buffer/codecbuffer_rgb888.cpp
I have fixed an error in CCodecBuffer_RGB888::WriteBlockRGBA function: Instead of using nChannelCount value (which is 3 for RGB texels), it uses the size of nChannelCount variable(which is 4 for most modern systems). It causes buffer overflow as the pointer goes after the buffer limits in addition to writing to the wrong location.
> Fixed destination pointer calculation when converting from RGBA to RGB

- build/windows_build_apps.bat
- build/windows_build_sdk.bat
- build/windows_build_sdk_2022.bat
I understand the build process isn't entirely streamlined, but this will make it so a developer with MSVC Community won't hit an unnecessary speed bump when using the windows build.bat files.
> windows build .bat files - Community edition support

- cmp_compressonatorlib/compressonator.cpp
Fixed calculation of buffer size for CMP_FORMAT_RG_16, CMP_FORMAT_RG_16F, CMP_FORMAT_R_16, CMP_FORMAT_R_16F formats
Fix for [issue#273](https://github.com/GPUOpen-Tools/compressonator/issues/273)
> Fixed calculation of buffer size 

- cmp_compressonatorlib/compress.cpp
Previous fix (https://github.com/GPUOpen-Tools/compressonator/pull/278) doesn't work if `CMP_FORMAT_ABGR_32F ` is a destination format. 
Sorry for not checking it earlier.
> Fixed GetCodecType for CMP_FORMAT_ABGR_32F format

- applications/_plugins/common/atiformats.cpp
Fix out of bound access of array `g_TextureTypeDesc`. Found with `-fsanitize=undefined`.
> Fix loop bound

- cmp_core/shaders/bc4_encode_kernel.cpp
`BC15options` may point to `BC15optionsDefault` which go out of scope at the end of if block.
> Fix dangling pointer

- applications/_plugins/cimage/dds/dds_dx10.cpp
> Fix DX10 header arraySize when saving cubemaps.
